#!/bin/bash

# We are using --no-i-r to show more accurate values in the progress output
rsync --recursive --human-readable --no-i-r --info=progress2 --exclude-from=".gitignore" --files-from="backup.txt" ./ ~/
