set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'seebi/tmux-colors-solarized'

set -g @colors-solarized 'light'

set-window-option -g mode-keys vi

# How to create a new window on the current directory in tmux?
# Link: https://unix.stackexchange.com/a/118381
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# RGB colors
# Link: https://github.com/alacritty/alacritty/issues/109#issuecomment-507026155
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Maybe this will increase the vim performance inside tmux
# Link: https://github.com/tmux/tmux/issues/353#issuecomment-265154018
set-option -g focus-events off
